### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by liupeng625** [aalavandhaann/go-icp_cython#1]
我在安装setup.py提示失败，是哪里出错了？
如下提示：

src/py_goicp.cpp(9143): error C2039: “exc_type”: 不是“_ts”的成员
d:\anconda\include\pystate.h(212): note: 参见“_ts”的声明
src/py_goicp.cpp(9144): error C2039: “exc_value”: 不是“_ts”的成员
d:\anconda\include\pystate.h(212): note: 参见“_ts”的声明
src/py_goicp.cpp(9145): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anconda\include\pystate.h(212): note: 参见“_ts”的声明
src/py_goicp.cpp(9146): error C2039: “exc_type”: 不是“_ts”的成员
d:\anconda\include\pystate.h(212): note: 参见“_ts”的声明
src/py_goicp.cpp(9147): error C2039: “exc_value”: 不是“_ts”的成员
d:\anconda\include\pystate.h(212): note: 参见“_ts”的声明
src/py_goicp.cpp(9148): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anconda\include\pystate.h(212): note: 参见“_ts”的声明

**Comment by aalavandhaann** [comment]
I am sorry but I couldn't understand what you are trying to convey

**Comment by liupeng625** [comment]
Sorry.I always failed to install 'setup.py'
such as :
src/py_goicp.cpp(9143): error C2039: “exc_type”: not a member of “_ts”

**Comment by aalavandhaann** [comment]
Did you install cython and autowrap as instructed in the readme? Or can you try pip install ```pip install py-goicp```

**Comment by Scrooge20291224** [comment]
This issue maybe relevant:
[https://github.com/cython/cython/issues/1955](url)

**Comment by aalavandhaann** [comment]
I found that the issue arises from outdated autowrap complication of pyx and cpp files. I will fix it tomorrow and update the pip packages as well.

**Comment by aalavandhaann** [comment]
Hey,

It should work now. I have updated the setup.py to compile the files everytime it is being installed. You can try either,
`pip install py-goicp --user` or `python setup.py build_ext --inplace`

However, please note that there will be issues compiling for python2 on Windows using VC9 and there is a huge possibility the installation might not succeed.  But it works fine with Ubuntu 18.04 and python2 using GCC. Also, I have tested on Windows 10 using anaconda and python 3.7, and it works just fine. 

Kindly let me know if you still see some issues. 

Regards,
#0K

**Comment by kakei-tao** [comment]
WARNING: Discarding https://files.pythonhosted.org/packages/19/1e/1b97b30d42b5139d6cd7b5fd17aeaa156d8bb970f4bebc27a8b25cce146f/py_goicp-0.0.4.tar.gz#sha256=3aacc6dd8bed01d13650dac1c64e66244305773faffffbe62278f0a7fb6175d1 (from https://pypi.org/simple/py-goicp/) (requires-python:>=2). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
"pip install py-goicp --user'' is failed....
Could you give me some advice?

**Comment by aalavandhaann** [comment]
Can you give more details please? Operating system, python version etc?

**Comment by kakei-tao** [comment]
Thanks for your reply.
My computer is Windows10, python3.6.

I can not install any version of the package. 
The error message for version 0.0.4 is: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
My solution is upgrade the 'pip'
But the result is not satisfied.

The error message for version 0.0.3 is:   cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
  py_goicp.cpp
  E:\python9\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2
I've configured the environment variables of computers.

Could you give me some advice? Thank you again!

**Comment by Zhang-ZP1998** [comment]
> 
Have you found a solution yet? I had the same problem
